export const authTheme = {
  fonts: {
    regular: "Inter_400Regular",
    semiBold: "Inter_600SemiBold",
    bold: "Inter_700Bold",
  },
  fontSizes: {
    appName: 34,
    subtitle: 14,
    input: 16,
    label: 14,
    button: 16,
    error: 12,
    footer: 14,
    small: 12,
  },
  colors: {
    primary: "#00BCD4",
    background: "#fff",
    textPrimary: "#111",
    textSecondary: "#666",
    inputBg: "#F8F9FA",
    inputBorder: "#E0E0E0",
    error: "#FF3B30",
    buttonText: "#fff",
    white: "#fff",
    black: "#000",
    border: "#E0E0E0",
    surface: "#F8F9FA",
  },
  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  borderRadius: 12,
};
