import { ClothingItem, FilterItem, TryOnHistoryItem } from '../types';

export const MOCK_CLOTHING_ITEMS: ClothingItem[] = [
  {
    id: '1',
    name: 'Black Evening Dress',
    brand: 'Zara',
    price: '$89.99',
    originalPrice: '$129.99',
    discount: '30%',
    rating: 4.8,
    reviews: 245,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80',
    category: 'Dresses',
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Black', 'Red', 'Navy'],
    isLiked: true,
  },
  {
    id: '2',
    name: 'Denim Jacket',
    brand: 'Levi\'s',
    price: '$69.99',
    originalPrice: '$99.99',
    discount: '30%',
    rating: 4.6,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80',
    category: 'Jackets',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Black', 'White'],
    isLiked: true,
  },
  {
    id: '3',
    name: 'White Sneakers',
    brand: 'Nike',
    price: '$129.99',
    originalPrice: '$159.99',
    discount: '19%',
    rating: 4.9,
    reviews: 312,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&q=80',
    category: 'Shoes',
    sizes: ['40', '41', '42', '43'],
    colors: ['White', 'Black'],
    isLiked: true,
  },
  {
    id: '4',
    name: 'Summer Floral Dress',
    brand: 'H&M',
    price: '$59.99',
    originalPrice: '$79.99',
    discount: '25%',
    rating: 4.5,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80',
    category: 'Dresses',
    sizes: ['XS', 'S', 'M'],
    colors: ['Multi', 'Pink', 'Blue'],
    isLiked: true,
  },
];

export const CURRENT_TRY_ON: ClothingItem = {
  id: 'current1',
  name: 'Casual Blazer',
  brand: 'Hugo Boss',
  price: '$199.99',
  originalPrice: '$299.99',
  discount: '33%',
  rating: 4.7,
  reviews: 421,
  description: 'Modern fit blazer with premium wool blend. Perfect for both casual and formal occasions.',
  materials: 'Wool 80%, Polyester 20%',
  care: 'Dry clean only',
  shipping: 'Free shipping & returns',
  image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80',
  category: 'Blazers',
  sizes: ['38', '40', '42', '44'],
  colors: ['Navy', 'Black', 'Gray'],
  isLiked: false,
};

export const FILTERS: FilterItem[] = [
  { id: 'none', name: 'None', icon: '👁️' },
  { id: 'studio', name: 'Studio', icon: '🎬' },
  { id: 'outdoor', name: 'Outdoor', icon: '🌳' },
  { id: 'night', name: 'Night', icon: '🌙' },
  { id: 'warm', name: 'Warm', icon: '☀️' },
  { id: 'cool', name: 'Cool', icon: '❄️' },
];

export const TRY_ON_HISTORY: TryOnHistoryItem[] = [
  {
    id: 'h1',
    name: 'Leather Jacket',
    brand: 'AllSaints',
    price: '$349.99',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80',
    date: 'Yesterday',
    liked: true,
  },
  {
    id: 'h2',
    name: 'Silk Dress',
    brand: 'Reformation',
    price: '$189.99',
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=400&q=80',
    date: '2 days ago',
    liked: false,
  },
  {
    id: 'h3',
    name: 'Sneakers',
    brand: 'Adidas',
    price: '$89.99',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
    date: '1 week ago',
    liked: true,
  },
];