import { SettingsSection } from '../types';
import {
  User,
  Shield,
  Lock,
  Palette,
  Users,
  UserPlus,
  HelpCircle,
  Info,
  Share2,
  Star,
  Bookmark,
  Eye,
  Video,
  Moon,
  Sun,
  Mail,
  Key,
  Trash2,
  LogOut,
  ShoppingBag,
  CreditCard,
  Package,
  MapPin,
  Coffee,
  Layout,
  Link,
  QrCode,
  CheckCircle,
  XCircle,
  AlertCircle,
} from 'lucide-react-native';

export const SETTINGS_SECTIONS: SettingsSection[] = [
  {
    title: 'Account',
    icon: <User size={22} />,
    items: [
      {
        id: 'edit_profile',
        title: 'Edit Profile',
        description: 'Change your profile information',
        icon: <User size={20} />,
        type: 'navigation',
        route: '/profile/edit',
      },
      {
        id: 'avatar_settings',
        title: 'Avatar Settings',
        description: 'Manage your 3D avatar',
        icon: <Layout size={20} />,
        type: 'navigation',
        route: '/avatar',
      },
      {
        id: 'change_password',
        title: 'Change Password',
        description: 'Update your account password',
        icon: <Key size={20} />,
        type: 'navigation',
        route: '/profile/change-password',
      },
      {
        id: 'delete_account',
        title: 'Delete Account',
        description: 'Permanently delete your account',
        icon: <Trash2 size={20} />,
        type: 'navigation',
        route: '/profile/delete-account',
      },
    ],
  },
  {
    title: 'Privacy & Security',
    icon: <Shield size={22} />,
    items: [
      {
        id: 'account_privacy',
        title: 'Account Privacy',
        description: 'Control who sees your content',
        icon: <Lock size={20} />,
        type: 'navigation',
        route: '/profile/privacy',
      },
      {
        id: 'blocked_users',
        title: 'Blocked Users',
        description: 'Manage blocked accounts',
        icon: <XCircle size={20} />,
        type: 'navigation',
        route: '/settings/blocked',
      },
      {
        id: 'activity_status',
        title: 'Activity Status',
        description: 'Show when you are active',
        icon: <Eye size={20} />,
        type: 'switch',
        value: true,
      },
      {
        id: 'read_receipts',
        title: 'Read Receipts',
        description: 'Let others see when you have read messages',
        icon: <CheckCircle size={20} />,
        type: 'switch',
        value: true,
      },
    ],
  },
  {
    title: 'Preferences',
    icon: <Palette size={22} />,
    items: [
      {
        id: 'theme',
        title: 'Theme',
        description: 'Light, Dark, or System default',
        icon: <Palette size={20} />,
        type: 'navigation',
        route: '/settings/theme',
      },
      {
        id: 'auto_play',
        title: 'Auto-Play Videos',
        description: 'Play videos automatically',
        icon: <Video size={20} />,
        type: 'switch',
        value: true,
      },
    ],
  },
  {
    title: 'Shopping & Wardrobe',
    icon: <ShoppingBag size={22} />,
    items: [
      {
        id: 'saved_items',
        title: 'Saved Items',
        description: 'View your saved outfits and products',
        icon: <Bookmark size={20} />,
        type: 'navigation',
        route: '/saved-items',
      },
      {
        id: 'payment_methods',
        title: 'Payment Methods',
        description: 'Manage your payment options',
        icon: <CreditCard size={20} />,
        type: 'navigation',
        route: '/settings/payments',
      },
      {
        id: 'order_history',
        title: 'Order History',
        description: 'View your past purchases',
        icon: <Package size={20} />,
        type: 'navigation',
        route: '/orders',
      },
    ],
  },
  {
    title: 'Social',
    icon: <Users size={22} />,
    items: [
      {
        id: 'follow_suggestions',
        title: 'Follow Suggestions',
        description: 'People you may know',
        icon: <UserPlus size={20} />,
        type: 'navigation',
        route: 'social/suggestions',
      },
      {
        id: 'invite_friends',
        title: 'Invite Friends',
        description: 'Invite friends to Wear Virtually',
        icon: <Share2 size={20} />,
        type: 'navigation',
        color: '#0095F6',
        route: 'social/qr-code',
      },
      {
        id: 'qr_code',
        title: 'QR Code',
        description: 'Your personal QR code',
        icon: <QrCode size={20} />,
        type: 'navigation',
        route: '/qr-code',
      },
      {
        id: 'link_sharing',
        title: 'Link Sharing',
        description: 'Share your profile link',
        icon: <Link size={20} />,
        type: 'action',
        color: '#0095F6',
      },
    ],
  },
  {
    title: 'Support',
    icon: <HelpCircle size={22} />,
    items: [
      {
        id: 'help_center',
        title: 'Help Center',
        description: 'Get help and support',
        icon: <HelpCircle size={20} />,
        type: 'navigation',
        route: 'support/help',
      },
      {
        id: 'report_problem',
        title: 'Report a Problem',
        description: 'Report issues or bugs',
        icon: <AlertCircle size={20} />,
        type: 'navigation',
        route: 'support/report',
      },
      {
        id: 'contact_us',
        title: 'Contact Us',
        description: 'Get in touch with our team',
        icon: <Mail size={20} />,
        type: 'navigation',
        route: 'support/contact',
      },
    ],
  },
  {
    title: 'About',
    icon: <Info size={22} />,
    items: [
      {
        id: 'about_app',
        title: 'About Wear Virtually',
        description: 'Version 2.0.1 • Build 2024.12.01',
        icon: <Info size={20} />,
        type: 'info',
      },
      {
        id: 'rate_app',
        title: 'Rate Wear Virtually',
        description: 'Leave a review on the App Store',
        icon: <Star size={20} />,
        type: 'action',
        color: '#FFB84D',
      },
      {
        id: 'share_app',
        title: 'Share App',
        description: 'Share with friends and family',
        icon: <Share2 size={20} />,
        type: 'action',
        color: '#0095F6',
      },
      {
        id: 'developer',
        title: 'Developer',
        description: 'Information about the developer',
        icon: <Coffee size={20} />,
        type: 'navigation',
        route: '/developer',
      },
    ],
  },
];